### ISSUE TITLE
Reorganize project structure

### ISSUE THREAD

**Issue by teisnet** [teisnet/shopvvs#3]
Create folders "Test" and "Libraries" in project root.
Move binary files to "/bin" folder in project root.
Centralize config and data files.

**Comment by teisnet** [comment]
Consider directory "/Output" for data output

**Comment by teisnet** [comment]
e54194a419dc255f46b9aef22ad856d60f7660c6

**Comment by Itsignatur** [comment]
Kære kunde 

Tak for din mail. 

Jeg er på sommerferie og er tilbage på kontoret igen den 30. Juli. Såfremt din henvendelse haster, kan du evt. kontakte mig på mobil: 2993 4488 eller sende en SMS 

Med venlig hilsen 

Lars Granhøj 

Systemudvikler / Developer 
45 2993 4488
IT Signatur ApS 
www.it-signatur.dk
